baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'La petite vadrouille'

[menu]
  [[menu.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menu.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
